### ISSUE TITLE
Openssh can't install

### ISSUE THREAD

**Issue by FGOD1983** [Towha/Termux#1]
I just moved to my new phone, and can't seem to install openssh on termux at this point.

```
$ ssh
The program ssh is not installed. Install it by executing:
 pkg install dropbear
or
 pkg install openssh
$ pkg install openssh
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package openssh
```

**Comment by samurmaykrr** [comment]
im not the best tech support but do this,

if you have installed termux totally new and or cleared it then first of all do 
`pkg upgrade` or `apt update`

https://github.com/termux/termux-packages/issues/164
see this, this is some common mistake but please be sure that you did this.

also see if any or some repo is disabled or not. 
https://wiki.termux.com/wiki/Package_Management
https://github.com/Towha/termux.sh#replace-domestic-software-source 

also try re running the script if it doesn't work maybe you can give some more details and i will look at it. I tried running the same command you ran it prompted whether i want to install it or not on clean install of termux.

**Comment by FGOD1983** [comment]
Seems I indeed forgot to do apt update first! Thx!
